-- Migration: Check auth.identities table structure
-- Executed at: 2026-04-10T05:18:43Z
-- Generated by Could Code

SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = 'auth' AND table_name = 'identities';
