-- Migration: Create translation_history table with RLS policies
-- Executed at: 2026-04-10T06:19:08Z
-- Generated by Could Code

-- Create the translation_history table
CREATE TABLE IF NOT EXISTS public.translation_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    source_text TEXT NOT NULL,
    translated_text TEXT NOT NULL,
    source_language TEXT NOT NULL,
    target_language TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.translation_history ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own translation history"
    ON public.translation_history FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own translation history"
    ON public.translation_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own translation history"
    ON public.translation_history FOR DELETE
    USING (auth.uid() = user_id);
